---
redis:
  master:
    replicaCount: 1
  replica:
    replicaCount: 2
  masterauth: password
  requirepass: password

namespace: 25844
nameOverride: ""
fullnameOverride: ""

image:
  repository: redis
  tag: 6.2.3-alpine
  pullPolicy: IfNotPresent
  pullSecrets:
  - name: registrysecret


service:
  type: ClusterIP
  port: 6379
  targetPort: 6379