apiVersion: v1
kind: Service
metadata:
  name: master-redis
  namespace: "{{ .Values.redis.namespace }}"
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
    type: master